name: Unit Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

      with:
        dotnet-version: 5.0

    - name: Restore dependencies
      working-directory: ./CleanArchMvc
      run: dotnet restore

    - name: Build Solution
      working-directory: ./CleanArchMvc
      run: dotnet build --no-restore

    - name: Run Domain Unit Tests
      working-directory: ./CleanArchMvc
      run: dotnet test ./CleanArchMvc.Domain.Tests/CleanArchMvc.Domain.Tests.csproj --no-build --verbosity m
